### ISSUE TITLE
How to fix load region prediction error

### ISSUE THREAD

**Issue by wenjiegong** [chipsalliance/Cores-SweRV-EL2#36]
Code snippet
address     :  instruction
`20003d84: auipc  x16, 0xfffc`
`20003d88: lw       x16, 776(x16)`

'lw' caused the load region prediction error. Because the value(20003d84+0xfffc000=2ffffd84) of x16 was not in the region of DCCM.

Is there a workaround to avoid the error? Thanks!

I use EL2 v1.4.

**Comment by aprnath** [comment]
Where have you installed the DCCM ? (What are the value of RV_DCCM_REGION in the common_defines.vh file?)
What is the value in MSCAUSE for the exception ?

Region prediction exception (MCAUSE==5, MSCAUSE==5) occurs if the effective address (x16 +776 in your case) falls in a different region than the base address (x16 in your case), and one of the two regions happens to be an 'internal' region (containing DCCM or PIC).  

Given your values above, this will happen if the DCCM or PIC is mapped to region 3, and your code is executing at the top of region two and your pointer generation is using current PC+relative to form the pointer. Can you confirm this?

The simplest workaround I can suggest is to form the pointer address in such a way to not need region crossing. If the DCCM is in region 3 make sure X16 is fully within region 3, and provide the appropriate offset. The EA for the load above is 0x3000008c. So best is to set up the DCCM base pointer to the start of the DCCM - at 0x30000000, for example. Use a "li" mnemonic, since your DCCM base is a known constant, instead of "la" - the latter tends to be PC relative.

If the address/offset mechanism is not in your control (compiler tries to be smarter), then avoid the text/code section to be adjacent to the DCCM (within 4K of the DCCM start/end).
